// new file servicenow
/**
 * Granular RBAC Permission Constants
 * Comprehensive permission system with component-level access control
 */

const PERMISSIONS = {
  // ===== User / Role / Permission Management =====
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_DELETE: 'users:delete',

  ROLES_READ: 'roles:read',
  ROLES_WRITE: 'roles:write',
  ROLES_DELETE: 'roles:delete',

  PERMISSIONS_READ: 'permissions:read',
  PERMISSIONS_WRITE: 'permissions:write',
  PERMISSIONS_DELETE: 'permissions:delete',

  // ===== Tickets =====
  TICKETS_READ: 'tickets:read',
  TICKETS_WRITE: 'tickets:write',
  TICKETS_DELETE: 'tickets:delete',

  // ===== SLA =====
  SLA_READ: 'sla:read',
  SLA_WRITE: 'sla:write',
  SLA_DELETE: 'sla:delete',

  // ===== Dashboard =====
  DASHBOARD_READ: 'dashboard:read',
  DASHBOARD_WRITE: 'dashboard:write',
  DASHBOARD_DELETE: 'dashboard:delete',

  // ===== Playbooks =====
  PLAYBOOKS_READ: 'playbooks:read',
  PLAYBOOKS_WRITE: 'playbooks:write',
  PLAYBOOKS_DELETE: 'playbooks:delete',

  // ===== AI RCA =====
  AIRCA_READ: 'aiRca:read',
  AIRCA_WRITE: 'aiRca:write',
  AIRCA_DELETE: 'aiRca:delete',

  // ===== Pattern & Duplicate Detector =====
  PATTERN_READ: 'patternDetector:read',
  PATTERN_WRITE: 'patternDetector:write',
  PATTERN_DELETE: 'patternDetector:delete',

  // ===== Playbook Recommender =====
  RECOMMENDER_READ: 'playbookRecommender:read',
  RECOMMENDER_WRITE: 'playbookRecommender:write',
  RECOMMENDER_DELETE: 'playbookRecommender:delete',

  // ===== Customer RCA Summary =====
  CRCA_READ: 'customerRcaSummary:read',
  CRCA_WRITE: 'customerRcaSummary:write',
  CRCA_DELETE: 'customerRcaSummary:delete',

  // ===== Alert Correlation =====
  CORRELATION_READ: 'alertCorrelation:read',
  CORRELATION_WRITE: 'alertCorrelation:write',
  CORRELATION_DELETE: 'alertCorrelation:delete',

  // ===== Compliance & Audit =====
  COMPLIANCE_READ: 'complianceAudit:read',
  COMPLIANCE_WRITE: 'complianceAudit:write',
  COMPLIANCE_DELETE: 'complianceAudit:delete',

  // ===== Chatbot =====
  CHATBOT_READ: 'chatbot:read',
  CHATBOT_WRITE: 'chatbot:write',
  CHATBOT_DELETE: 'chatbot:delete'
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

/**
 * Role-based permission mappings
 * - Existing roles preserved (admin, user)
 * - Adds manager, support_agent, viewer
 * - Adds per-component roles for granular access
 */
const ROLE_PERMISSIONS = {
  // ===== Existing broad roles =====

  // Full access across the platform
  admin: [
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE, PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_READ, PERMISSIONS.ROLES_WRITE, PERMISSIONS.ROLES_DELETE,
    PERMISSIONS.PERMISSIONS_READ, PERMISSIONS.PERMISSIONS_WRITE, PERMISSIONS.PERMISSIONS_DELETE,
    PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE, PERMISSIONS.TICKETS_DELETE,
    PERMISSIONS.SLA_READ, PERMISSIONS.SLA_WRITE, PERMISSIONS.SLA_DELETE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.DASHBOARD_WRITE, PERMISSIONS.DASHBOARD_DELETE,
    PERMISSIONS.PLAYBOOKS_READ, PERMISSIONS.PLAYBOOKS_WRITE, PERMISSIONS.PLAYBOOKS_DELETE,
    PERMISSIONS.AIRCA_READ, PERMISSIONS.AIRCA_WRITE, PERMISSIONS.AIRCA_DELETE,
    PERMISSIONS.PATTERN_READ, PERMISSIONS.PATTERN_WRITE, PERMISSIONS.PATTERN_DELETE,
    PERMISSIONS.RECOMMENDER_READ, PERMISSIONS.RECOMMENDER_WRITE, PERMISSIONS.RECOMMENDER_DELETE,
    PERMISSIONS.CRCA_READ, PERMISSIONS.CRCA_WRITE, PERMISSIONS.CRCA_DELETE,
    PERMISSIONS.CORRELATION_READ, PERMISSIONS.CORRELATION_WRITE, PERMISSIONS.CORRELATION_DELETE,
    PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_WRITE, PERMISSIONS.COMPLIANCE_DELETE,
    PERMISSIONS.CHATBOT_READ, PERMISSIONS.CHATBOT_WRITE, PERMISSIONS.CHATBOT_DELETE
  ],

  // Manager: broad access but non-destructive (no :delete)
  manager: [
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
    PERMISSIONS.ROLES_READ, PERMISSIONS.ROLES_WRITE,
    PERMISSIONS.PERMISSIONS_READ, PERMISSIONS.PERMISSIONS_WRITE,
    PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.SLA_READ, PERMISSIONS.SLA_WRITE,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.DASHBOARD_WRITE,
    PERMISSIONS.PLAYBOOKS_READ, PERMISSIONS.PLAYBOOKS_WRITE,
    PERMISSIONS.AIRCA_READ, PERMISSIONS.AIRCA_WRITE,
    PERMISSIONS.PATTERN_READ, PERMISSIONS.PATTERN_WRITE,
    PERMISSIONS.RECOMMENDER_READ, PERMISSIONS.RECOMMENDER_WRITE,
    PERMISSIONS.CRCA_READ, PERMISSIONS.CRCA_WRITE,
    PERMISSIONS.CORRELATION_READ, PERMISSIONS.CORRELATION_WRITE,
    PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_WRITE,
    PERMISSIONS.CHATBOT_READ, PERMISSIONS.CHATBOT_WRITE
  ],

  // Support Agent: frontline operations
  support_agent: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.SLA_READ,
    PERMISSIONS.PLAYBOOKS_READ,
    PERMISSIONS.RECOMMENDER_READ,
    PERMISSIONS.CHATBOT_READ
  ],

  // User: standard product user
  user: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.SLA_READ,
    PERMISSIONS.PLAYBOOKS_READ,
    PERMISSIONS.RECOMMENDER_READ,
    PERMISSIONS.CHATBOT_READ
  ],

  // Viewer: read-only everywhere
  viewer: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.PERMISSIONS_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.SLA_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PLAYBOOKS_READ,
    PERMISSIONS.AIRCA_READ,
    PERMISSIONS.PATTERN_READ,
    PERMISSIONS.RECOMMENDER_READ,
    PERMISSIONS.CRCA_READ,
    PERMISSIONS.CORRELATION_READ,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.CHATBOT_READ
  ],

  // ===== Per-component roles (granular access) =====
  // ---- Dashboard ----
  dashboard_reader: [PERMISSIONS.DASHBOARD_READ],
  dashboard_editor: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.DASHBOARD_WRITE],
  dashboard_owner:  [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.DASHBOARD_WRITE, PERMISSIONS.DASHBOARD_DELETE],

  // ---- Tickets ----
  tickets_reader: [PERMISSIONS.TICKETS_READ],
  tickets_editor: [PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE],
  tickets_owner:  [PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE, PERMISSIONS.TICKETS_DELETE],

  // ---- SLA ----
  sla_reader: [PERMISSIONS.SLA_READ],
  sla_editor: [PERMISSIONS.SLA_READ, PERMISSIONS.SLA_WRITE],
  sla_owner:  [PERMISSIONS.SLA_READ, PERMISSIONS.SLA_WRITE, PERMISSIONS.SLA_DELETE],

  // ---- Playbooks ----
  playbooks_reader: [PERMISSIONS.PLAYBOOKS_READ],
  playbooks_editor: [PERMISSIONS.PLAYBOOKS_READ, PERMISSIONS.PLAYBOOKS_WRITE],
  playbooks_owner:  [PERMISSIONS.PLAYBOOKS_READ, PERMISSIONS.PLAYBOOKS_WRITE, PERMISSIONS.PLAYBOOKS_DELETE],

  // ---- AI RCA ----
  aiRca_reader: [PERMISSIONS.AIRCA_READ],
  aiRca_editor: [PERMISSIONS.AIRCA_READ, PERMISSIONS.AIRCA_WRITE],
  aiRca_owner:  [PERMISSIONS.AIRCA_READ, PERMISSIONS.AIRCA_WRITE, PERMISSIONS.AIRCA_DELETE],

  // ---- Pattern Detector ----
  patternDetector_reader: [PERMISSIONS.PATTERN_READ],
  patternDetector_editor: [PERMISSIONS.PATTERN_READ, PERMISSIONS.PATTERN_WRITE],
  patternDetector_owner:  [PERMISSIONS.PATTERN_READ, PERMISSIONS.PATTERN_WRITE, PERMISSIONS.PATTERN_DELETE],

  // ---- Playbook Recommender ----
  playbookRecommender_reader: [PERMISSIONS.RECOMMENDER_READ],
  playbookRecommender_editor: [PERMISSIONS.RECOMMENDER_READ, PERMISSIONS.RECOMMENDER_WRITE],
  playbookRecommender_owner:  [PERMISSIONS.RECOMMENDER_READ, PERMISSIONS.RECOMMENDER_WRITE, PERMISSIONS.RECOMMENDER_DELETE],

  // ---- Customer RCA Summary ----
  customerRcaSummary_reader: [PERMISSIONS.CRCA_READ],
  customerRcaSummary_editor: [PERMISSIONS.CRCA_READ, PERMISSIONS.CRCA_WRITE],
  customerRcaSummary_owner:  [PERMISSIONS.CRCA_READ, PERMISSIONS.CRCA_WRITE, PERMISSIONS.CRCA_DELETE],

  // ---- Alert Correlation ----
  alertCorrelation_reader: [PERMISSIONS.CORRELATION_READ],
  alertCorrelation_editor: [PERMISSIONS.CORRELATION_READ, PERMISSIONS.CORRELATION_WRITE],
  alertCorrelation_owner:  [PERMISSIONS.CORRELATION_READ, PERMISSIONS.CORRELATION_WRITE, PERMISSIONS.CORRELATION_DELETE],

  // ---- Compliance & Audit ----
  complianceAudit_reader: [PERMISSIONS.COMPLIANCE_READ],
  complianceAudit_editor: [PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_WRITE],
  complianceAudit_owner:  [PERMISSIONS.COMPLIANCE_READ, PERMISSIONS.COMPLIANCE_WRITE, PERMISSIONS.COMPLIANCE_DELETE],

  // ---- Chatbot ----
  chatbot_reader: [PERMISSIONS.CHATBOT_READ],
  chatbot_editor: [PERMISSIONS.CHATBOT_READ, PERMISSIONS.CHATBOT_WRITE],
  chatbot_owner:  [PERMISSIONS.CHATBOT_READ, PERMISSIONS.CHATBOT_WRITE, PERMISSIONS.CHATBOT_DELETE],

  // ---- User Management (users/roles/permissions combined) ----
  userManagement_reader: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.PERMISSIONS_READ
  ],
  userManagement_editor: [
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
    PERMISSIONS.ROLES_READ, PERMISSIONS.ROLES_WRITE,
    PERMISSIONS.PERMISSIONS_READ, PERMISSIONS.PERMISSIONS_WRITE
  ],
  userManagement_owner: [
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE, PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_READ, PERMISSIONS.ROLES_WRITE, PERMISSIONS.ROLES_DELETE,
    PERMISSIONS.PERMISSIONS_READ, PERMISSIONS.PERMISSIONS_WRITE, PERMISSIONS.PERMISSIONS_DELETE
  ]
};

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE_PERMISSIONS
};
